### ISSUE TITLE
Persisting of empty Integer values fails

### ISSUE THREAD

**Issue by elDub** [graphiti-api/graphiti#67]
When clearing an existing integer value in the client, Spraypaint sends an empty string to the server to represent the change, however Graphiti doesn't like an empty string (nor `'nil'` or `'null'`).

```
ERROR: Graphiti::Errors::TypecastFailed: MMApi::AssetResource: Failed typecasting :year! Given "" but the following error was raised:

invalid value for Integer(): ""

/Users/lonnie/Projects/MachineTools/.mt3.gems/gems/dry-types-0.13.4/lib/dry/types/constructor.rb:54:in `Integer'
/Users/lonnie/Projects/MachineTools/.mt3.gems/gems/dry-types-0.13.4/lib/dry/types/constructor.rb:54:in `[]'
/Users/lonnie/Projects/MachineTools/.mt3.gems/gems/dry-types-0.13.4/lib/dry/types/constructor.rb:54:in `call'
/Users/lonnie/Projects/MachineTools/.mt3.gems/bundler/gems/graphiti-ae91899884f0/lib/graphiti/types.rb:60:in `block in <class:Types>'
```

```ruby
class MyResource < Graphiti::Resource
  attribute :year, :integer
end
```

```ruby
irb(main):001:0> Dry::Types['coercible.integer']['']
ArgumentError: invalid value for Integer(): ""
    from (irb):1
irb(main):002:0> Dry::Types['coercible.integer']['nil']
ArgumentError: invalid value for Integer(): "nil"
    from (irb):2
irb(main):003:0> Dry::Types['coercible.integer']['null']
ArgumentError: invalid value for Integer(): "null"
	from (irb):3
```

**Comment by richmolj** [comment]
Addressed in Spraypaint
